### ISSUE TITLE
Implement User Authentication

### ISSUE THREAD

**Issue by jinyung2** [Hadiasemi/Crypto-Tracker#11]
Estimate: 3 hours

Work with the backend to figure out what technologies to implement authentication with, and get a working authentication logic and routing working from Login/Signup page.

**Comment by jinyung2** [comment]
Time Spent: 1 hour
Researched into different methods of implementing authentication using tokens.

sessionStorage: active only in 1 tab, vunerable to attacks since js based
localStorage: active for the whole browser and stored in the browser localStorage, also vuneralbe to attacks since js based
backend session: old school method, too much coupling between frontend and backend
cookies (httpOnly): not vunerable to js based attacks, but still vunerable to other attacks

I will mostly likely use localStorage with very short duration tokens (< 15 min expiration time), and possibly use refresh tokens.

**Comment by jinyung2** [comment]
Time Spent: 1 hour

Spent some more time doing research in terms of how to structure authentication
Will be using react context api to create context provider and the useContext hook to import the authentication related state (or token) which can be used in others of application to protect routes and/or cause redirection behavior depending whether token is valid/active or not.

**Comment by jinyung2** [comment]
Time Spent: 6 hours

Spent quite a lot of time trying to figure out how set up the AuthContext API, and determine what data the auth context needs to hold. Also took some time to set up the token expiration logic and getting all the route protection setup using the `isLoggedIn` state from the auth context. 
Hitting the backend endpoints for `/signin` and `/signup` successfully and performing error handling by setting the `error` state on the `SignUpLogIn` component to a default error message.

**Comment by jinyung2** [comment]
@WeslyOrtega atm I currently have it set up for the token stored in localStorage on the frontend to expire in 10 mins (I think that was the specs on your api docs). We can just agree on this and move forward, or you could return the actual expiration time in the response if you think the time duration may change in future. Let me know what you think

**Comment by WeslyOrtega** [comment]
I think we can just agree on this. 
I don't think I'll be changing the expiration time, unless you think there is a more fitting time.
