### ISSUE TITLE
Implement Info Bar and populate with backend data

### ISSUE THREAD

**Issue by jinyung2** [Hadiasemi/Crypto-Tracker#29]
Estimate: 1 hour

When hitting an endpoint for a specified crypto, the info on the bottom needs to be updated. 

Still need to discuss what info to show exactly (volume? market cap? etc... possibly check other websites or apps ie. robinhood)

**Comment by WeslyOrtega** [comment]
Time Spent: 3 Hours

Sorry, I'm slow as bricks
