### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by jinyung2** [Hadiasemi/Crypto-Tracker#34]
Estimate: 8 hours

- Find more fitting font styles, sizes, weights
- Possibly Animations for smoother transitions
- Better responsive design updates

**Comment by jinyung2** [comment]
Time Spent: 2 hours

fixed various CSS in the application to account for responsive design and animations for UX improvements

**Comment by jinyung2** [comment]
Time Spent: 2 hours

Added in some animations into 404 page, as well as some utilizing react memo-ization for graph to prevent constant re-rendering.

**Comment by jinyung2** [comment]
Time Spent: 2 hours

Fixed some responsive design in the login and signup page, rendered vertical divider line as a div with a width of 1px instead of a border (in order to better center component).

**Comment by jinyung2** [comment]
Time Spent: 1 hour

Implemented smooth scroll to top when selecting a new crypto from watchlist

**Comment by jinyung2** [comment]
Time Spent: 1 hour

Graph in the Dashboard component had some unnecessary re-rendering problems. Ended up learning how to use useCallback hook on a function for toggling the graph type and fed in a dependency for when it shouldn't use the memo-ized version (so that the Graph component does re-render).

**Comment by tessa-tapmongkol** [comment]
Looks good to me!

**Comment by jinyung2** [comment]
Closing this now since there won't be anymore UI/UX updates at this point for sprint #3.
