### ISSUE TITLE
Create Search/NavBar Component

### ISSUE THREAD

**Issue by tessa-tapmongkol** [Hadiasemi/Crypto-Tracker#7]
Estimated Time to Complete: 3 hours

Layout: https://www.figma.com/file/MqulgZsxN8o4MrhXMbaP05/Untitled?node-id=0%3A1

- [x] Connect backend API to fetch results for the search bar
- [x] Create options button specific options TBD
- [x] Create profile button specific profile options TBD

**Comment by tessa-tapmongkol** [comment]
Time: 2 hours (had to research how to use autosuggest.js)

**Comment by jinyung2** [comment]
@tessa-tapmongkol I was working on User Authentication and realized we might need a Logout button on the Navbar?

**Comment by jinyung2** [comment]
Implemented re-rendering of app using `onSuggestionSelected` prop in the `AutoSuggest` component.
